version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sysplane-center
    binary: sysplane-center
    main: ./cmd/sysplane-center
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/jimmicro/version.GitTag={{ .Tag }}'
      - -X 'github.com/jimmicro/version.BuildTime={{ .Date }}'

  - id: sysplane-proxy
    binary: sysplane-proxy
    main: ./cmd/sysplane-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/jimmicro/version.GitTag={{ .Tag }}'
      - -X 'github.com/jimmicro/version.BuildTime={{ .Date }}'

  - id: sysplane-agent
    binary: sysplane-agent
    main: ./cmd/sysplane-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X 'github.com/jimmicro/version.GitTag={{ .Tag }}'
      - -X 'github.com/jimmicro/version.BuildTime={{ .Date }}'

archives:
  - id: center
    ids: [sysplane-center]
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: proxy
    ids: [sysplane-proxy]
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: agent
    ids: [sysplane-agent]
    formats:
      - binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
